apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp-deployment
  #namespace: production  # if you do not define namesapce it will take it as default
  labels:
    app: mynodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynodeapp
  template:
    metadata:
      labels:
        app: mynodeapp
    spec:
      containers:
      - name: mynodeapp
        image: devopsadmin786/mynodeapp:latest
        ports:
        - containerPort: 3000
  # strategy:
  #  type: RollingUpdate
  #  rollingUpdate:
  #    maxUnavailable: 1
