apiVersion: v1
kind: Service
metadata:
  name: mynodeapp-svc
spec:
  selector:
    app: mynodeapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 32112
  type: LoadBalancer
